onboarding = false

[keys]
switch_tab = "cmd+1..9"
focus_pane_left = "cmd+h"
focus_pane_down = "cmd+j"
focus_pane_up = "cmd+k"
focus_pane_right = "cmd+l"
resize_pane_left = "cmd+shift+h"
resize_pane_down = "cmd+shift+j"
resize_pane_up = "cmd+shift+k"
resize_pane_right = "cmd+shift+l"
close_pane = "cmd+x"
split_vertical = "cmd+alt+l"
split_horizontal = "cmd+alt+j"

[ui.sound]
enabled = false

[ui]
status_indicators = "dots"

[ui.toast]
delivery = "off"
